### ISSUE TITLE
Can't run it with `docker` and `bretfisher/jekyll-serve`

### ISSUE THREAD

**Issue by maifeeulasad** [agusmakmun/agusmakmun.github.io#78]
Trying to add docker support for local system:
`docker-compose.yml`
```yaml
version: '2.4'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '80:4000'
```

But it crashes. Here is the full log:
```
2023-04-19 19:42:28 Bundler 2.4.12 is running, but your lockfile was generated with 1.17.2. Installing Bundler 1.17.2 and restarting using that version.
2023-04-19 19:42:42 Fetching gem metadata from https://rubygems.org/.
2023-04-19 19:42:42 Fetching bundler 1.17.2
2023-04-19 19:42:42 Installing bundler 1.17.2
2023-04-19 19:42:46 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:42:46 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:42:46 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:42:46 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
..................
..................
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:02 Fetching gem metadata from https://rubygems.org/.........
2023-04-19 19:43:03 Using minitest 5.15.0
2023-04-19 19:43:03 Using bundler 1.17.2
2023-04-19 19:43:03 Using colorator 1.1.0
2023-04-19 19:43:03 Using eventmachine 1.2.7
2023-04-19 19:43:03 Using http_parser.rb 0.8.0
2023-04-19 19:43:03 Using ffi 1.15.5
2023-04-19 19:43:03 Fetching zeitwerk 2.5.4
2023-04-19 19:43:03 Fetching faraday-net_http_persistent 1.2.0
2023-04-19 19:43:03 Fetching public_suffix 4.0.6
2023-04-19 19:43:03 Fetching faraday-excon 1.1.0
2023-04-19 19:43:03 Using ruby2_keywords 0.0.5
2023-04-19 19:43:03 Fetching unf_ext 0.0.8
2023-04-19 19:43:03 Fetching faraday-em_synchrony 1.0.0
2023-04-19 19:43:03 Using forwardable-extended 2.6.0
2023-04-19 19:43:03 Fetching concurrent-ruby 1.1.9
2023-04-19 19:43:03 Fetching faraday-em_http 1.0.0
2023-04-19 19:43:03 Fetching faraday-net_http 1.0.1
2023-04-19 19:43:03 Fetching thread_safe 0.3.6
2023-04-19 19:43:03 Fetching faraday-httpclient 1.0.1
2023-04-19 19:43:03 Fetching execjs 2.8.1
2023-04-19 19:43:03 Fetching faraday-patron 1.0.0
2023-04-19 19:43:03 Fetching coffee-script-source 1.11.1
2023-04-19 19:43:03 Fetching faraday-rack 1.0.0
2023-04-19 19:43:03 Fetching faraday-retry 1.0.3
2023-04-19 19:43:03 Fetching multipart-post 2.1.1
2023-04-19 19:43:03 Fetching gemoji 3.0.1
2023-04-19 19:43:03 Fetching rb-fsevent 0.11.1
2023-04-19 19:43:04 Installing faraday-excon 1.1.0
2023-04-19 19:43:04 Installing faraday-httpclient 1.0.1
2023-04-19 19:43:04 Installing faraday-em_synchrony 1.0.0
2023-04-19 19:43:04 Installing faraday-em_http 1.0.0
2023-04-19 19:43:04 Installing faraday-net_http_persistent 1.2.0
2023-04-19 19:43:04 Installing faraday-net_http 1.0.1
2023-04-19 19:43:04 Installing faraday-patron 1.0.0
2023-04-19 19:43:04 Installing faraday-retry 1.0.3
2023-04-19 19:43:04 Installing faraday-rack 1.0.0
2023-04-19 19:43:04 Installing multipart-post 2.1.1
2023-04-19 19:43:04 Installing execjs 2.8.1
2023-04-19 19:43:04 Installing zeitwerk 2.5.4
2023-04-19 19:43:04 Installing gemoji 3.0.1
2023-04-19 19:43:04 Installing rb-fsevent 0.11.1
2023-04-19 19:43:04 Installing coffee-script-source 1.11.1
2023-04-19 19:43:04 Installing public_suffix 4.0.6
2023-04-19 19:43:04 Installing thread_safe 0.3.6
2023-04-19 19:43:05 Using rexml 3.2.5
2023-04-19 19:43:05 Fetching mercenary 0.3.6
2023-04-19 19:43:05 Using safe_yaml 1.0.5
2023-04-19 19:43:05 Using racc 1.6.0
2023-04-19 19:43:05 Fetching rouge 3.26.0
2023-04-19 19:43:05 Fetching jekyll-paginate 1.1.0
2023-04-19 19:43:05 Fetching liquid 4.0.3
2023-04-19 19:43:05 Using em-websocket 0.5.3
2023-04-19 19:43:05 Fetching unicode-display_width 1.8.0
2023-04-19 19:43:05 Using rb-inotify 0.10.1
2023-04-19 19:43:05 Fetching rubyzip 2.3.2
2023-04-19 19:43:05 Fetching jekyll-swiss 1.0.0
2023-04-19 19:43:05 Fetching ethon 0.15.0
2023-04-19 19:43:05 Using pathutil 0.16.2
2023-04-19 19:43:05 Fetching kramdown 2.3.1
2023-04-19 19:43:05 Fetching coffee-script 2.4.1
2023-04-19 19:43:05 Installing unf_ext 0.0.8 with native extensions
2023-04-19 19:43:05 Fetching faraday-multipart 1.0.3
2023-04-19 19:43:05 Fetching nokogiri 1.13.3 (x86_64-linux)
2023-04-19 19:43:05 Installing concurrent-ruby 1.1.9
2023-04-19 19:43:05 Fetching sass-listen 4.0.0
2023-04-19 19:43:05 Fetching listen 3.7.1
2023-04-19 19:43:06 Installing jekyll-paginate 1.1.0
2023-04-19 19:43:06 Installing coffee-script 2.4.1
2023-04-19 19:43:06 Installing unicode-display_width 1.8.0
2023-04-19 19:43:06 Installing jekyll-swiss 1.0.0
2023-04-19 19:43:06 Installing faraday-multipart 1.0.3
2023-04-19 19:43:06 Installing mercenary 0.3.6
2023-04-19 19:43:06 Installing listen 3.7.1
2023-04-19 19:43:06 Installing rubyzip 2.3.2
2023-04-19 19:43:06 Fetching jekyll-coffeescript 1.1.1
2023-04-19 19:43:06 Installing ethon 0.15.0
2023-04-19 19:43:06 Installing sass-listen 4.0.0
2023-04-19 19:43:06 Installing liquid 4.0.3
2023-04-19 19:43:06 Installing kramdown 2.3.1
2023-04-19 19:43:07 Fetching terminal-table 1.8.0
2023-04-19 19:43:07 Fetching faraday 1.10.0
2023-04-19 19:43:07 Installing jekyll-coffeescript 1.1.1
2023-04-19 19:43:07 Fetching addressable 2.8.0
2023-04-19 19:43:07 Installing terminal-table 1.8.0
2023-04-19 19:43:07 Installing faraday 1.10.0
2023-04-19 19:43:08 Fetching tzinfo 1.2.9
2023-04-19 19:43:08 Installing rouge 3.26.0
2023-04-19 19:43:08 Fetching sass 3.7.4
2023-04-19 19:43:08 Using jekyll-watch 2.2.1
2023-04-19 19:43:08 Installing addressable 2.8.0
2023-04-19 19:43:08 Installing tzinfo 1.2.9
2023-04-19 19:43:09 Installing sass 3.7.4
2023-04-19 19:43:09 Fetching typhoeus 1.4.0
2023-04-19 19:43:09 Fetching sawyer 0.8.2
2023-04-19 19:43:10 Installing typhoeus 1.4.0
2023-04-19 19:43:10 Installing sawyer 0.8.2
2023-04-19 19:43:10 Fetching i18n 0.9.5
2023-04-19 19:43:10 Fetching octokit 4.22.0
2023-04-19 19:43:10 Installing i18n 0.9.5
2023-04-19 19:43:11 Installing octokit 4.22.0
2023-04-19 19:43:11 Fetching jekyll-sass-converter 1.5.2
2023-04-19 19:43:11 Installing jekyll-sass-converter 1.5.2
2023-04-19 19:43:11 Fetching ruby-enum 0.9.0
2023-04-19 19:43:11 Fetching activesupport 6.0.4.6
2023-04-19 19:43:12 Fetching jekyll-gist 1.5.0
2023-04-19 19:43:12 Installing nokogiri 1.13.3 (x86_64-linux)
2023-04-19 19:43:12 Installing jekyll-gist 1.5.0
2023-04-19 19:43:12 Installing ruby-enum 0.9.0
2023-04-19 19:43:12 Installing activesupport 6.0.4.6
2023-04-19 19:43:13 Fetching commonmarker 0.17.13
2023-04-19 19:43:13 Using kramdown-parser-gfm 1.1.0
2023-04-19 19:43:13 Fetching jekyll 3.9.0
2023-04-19 19:43:13 Installing commonmarker 0.17.13 with native extensions
2023-04-19 19:43:14 Installing jekyll 3.9.0
2023-04-19 19:43:14 Fetching unf 0.1.4
2023-04-19 19:43:14 Fetching jekyll-avatar 0.7.0
2023-04-19 19:43:14 Fetching jekyll-optional-front-matter 0.3.2
2023-04-19 19:43:14 Fetching jekyll-redirect-from 0.16.0
2023-04-19 19:43:14 Fetching jekyll-remote-theme 0.4.3
2023-04-19 19:43:14 Fetching jekyll-default-layout 0.1.4
2023-04-19 19:43:14 Fetching jekyll-feed 0.15.1
2023-04-19 19:43:14 Fetching jekyll-include-cache 0.2.1
2023-04-19 19:43:14 Fetching jekyll-relative-links 0.6.1
2023-04-19 19:43:14 Fetching jekyll-sitemap 1.4.0
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
2023-04-19 19:43:01 /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
...............
...............
2023-04-19 19:43:40        Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
2023-04-19 19:43:52 /usr/local/bundle/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read': no implicit conversion of Hash into Integer (TypeError)
2023-04-19 19:43:52 from /usr/local/bundle/gems/pathutil-0.16.2/lib/pathutil.rb:502:in `read'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:75:in `proc_version'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/utils/platforms.rb:40:in `bash_on_windows?'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:77:in `watch'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:43:in `process'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
2023-04-19 19:43:52 from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
2023-04-19 19:43:52 from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
2023-04-19 19:43:52 from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
2023-04-19 19:43:52 from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
2023-04-19 19:43:52 from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
2023-04-19 19:43:52 from /usr/local/bundle/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
2023-04-19 19:43:52 from /usr/local/bundle/bin/jekyll:25:in `load'
2023-04-19 19:43:52 from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `load'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in `run'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in `exec'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in `dispatch'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in `start'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
2023-04-19 19:43:52 from /usr/local/bundle/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
2023-04-19 19:43:52 from /usr/local/bin/bundle:25:in `load'
2023-04-19 19:43:52 from /usr/local/bin/bundle:25:in `<main>'
```

Related issue: #46 

Full log available here: https://pastebin.mozilla.org/VULqQdxB

**Comment by maifeeulasad** [comment]
I've copied the docker file from here: https://bjm.me.uk/blog/testing-github-pages-locally-docker/
